name: "✨ Feature request"
description: "Suggest an idea or enhancement"
title: "[Feature] "
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: What do you want to see?
      description: Be specific about the feature or enhancement you're proposing.
      placeholder: |
        I'd like a keyboard shortcut to export directly to PDF.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Why is this useful?
      description: Describe the problem this feature would solve or improve.
